version: '3.8'
services:
  postgres:
    image: postgres:10.3
    restart: always
    environment:
      - POSTGRES_USER=daniflav
      - POSTGRES_PASSWORD=dani@2020
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  app:
    build: .
    command: npm run server
    ports: 
      - "3001:3001"
    volumes:
      - .:/usr/src/app
      - ./uploads:/usr/src/app/uploads
    environment:
      - DATABASE_URL=postgresql://daniflav:dani@2020@postgres:5432/mydb?schema=public
  
volumes:
  postgres: